#!/bin/bash
set -e

# ==============================================================================
# Home Assistant Add-on: ntfy
# Runs the ntfy notification service
# ==============================================================================

echo "[INFO] Starting ntfy..."

# Read configuration from options.json
OPTIONS_FILE="/data/options.json"

if [ ! -f "$OPTIONS_FILE" ]; then
    echo "[ERROR] Configuration file not found: $OPTIONS_FILE"
    exit 1
fi

# Helper function to get config values
get_config() {
    local key="$1"
    local default="$2"
    local value=$(jq -r ".$key // empty" "$OPTIONS_FILE" 2>/dev/null)
    if [ -z "$value" ] || [ "$value" = "null" ]; then
        echo "$default"
    else
        echo "$value"
    fi
}

# Get configuration from add-on options
PORT=$(get_config "port" "8080")
BASE_URL=$(get_config "base_url" "")
AUTH_FILE=$(get_config "auth_file" "")
AUTH_DEFAULT_ACCESS=$(get_config "auth_default_access" "read-write")
CACHE_FILE=$(get_config "cache_file" "/data/cache.db")
LOG_LEVEL=$(get_config "log_level" "INFO")
BEHIND_PROXY=$(get_config "behind_proxy" "false")
ENABLE_SIGNUP=$(get_config "enable_signup" "false")
ENABLE_LOGIN=$(get_config "enable_login" "false")
ENABLE_RESERVATIONS=$(get_config "enable_reservations" "false")

# Create configuration directory
mkdir -p /data/config

# Generate ntfy configuration file
CONFIG_FILE="/data/config/server.yml"

echo "[INFO] Generating ntfy configuration..."

cat > "${CONFIG_FILE}" <<EOF
# ntfy server configuration
# Generated by Home Assistant Add-on

# Listen address and port
listen-http: ":${PORT}"

# Cache settings
cache-file: "${CACHE_FILE}"
cache-duration: "12h"

# Log settings
log-level: ${LOG_LEVEL,,}
log-format: text

# Authentication settings
auth-default-access: "${AUTH_DEFAULT_ACCESS}"

# CORS settings for Home Assistant integration
cors-allowed-origins: ["*"]

# Web app settings
web-root: disable

# Health check
enable-metrics: false
EOF

# Add optional base URL
if [ -n "${BASE_URL}" ] && [ "${BASE_URL}" != "" ]; then
    echo "base-url: \"${BASE_URL}\"" >> "${CONFIG_FILE}"
fi

# Add optional behind proxy setting
if [ "${BEHIND_PROXY}" = "true" ]; then
    echo "behind-proxy: true" >> "${CONFIG_FILE}"
fi

# Add optional authentication file
if [ -n "${AUTH_FILE}" ] && [ "${AUTH_FILE}" != "" ]; then
    echo "auth-file: \"/data/${AUTH_FILE}\"" >> "${CONFIG_FILE}"
    
    # Create auth file if it doesn't exist
    if [ ! -f "/data/${AUTH_FILE}" ]; then
        echo "[INFO] Creating authentication file: /data/${AUTH_FILE}"
        touch "/data/${AUTH_FILE}"
        chown ntfy:ntfy "/data/${AUTH_FILE}"
        chmod 600 "/data/${AUTH_FILE}"
    fi
fi

# Add optional signup/login settings
if [ "${ENABLE_SIGNUP}" = "true" ]; then
    echo "enable-signup: true" >> "${CONFIG_FILE}"
fi

if [ "${ENABLE_LOGIN}" = "true" ]; then
    echo "enable-login: true" >> "${CONFIG_FILE}"
fi

if [ "${ENABLE_RESERVATIONS}" = "true" ]; then
    echo "enable-reservations: true" >> "${CONFIG_FILE}"
fi

# Ensure data directory permissions
chown -R ntfy:ntfy /data
chmod -R 755 /data

# Log the configuration (without sensitive data)
echo "[INFO] ntfy configuration:"
echo "[INFO] Port: ${PORT}"
echo "[INFO] Log Level: ${LOG_LEVEL}"
echo "[INFO] Authentication: $([ -n "${AUTH_FILE}" ] && echo "Enabled" || echo "Disabled")"
echo "[INFO] Behind Proxy: ${BEHIND_PROXY}"

# Start ntfy server as ntfy user
echo "[INFO] Starting ntfy server..."
exec su-exec ntfy /usr/local/bin/ntfy serve --config="${CONFIG_FILE}"